version: '3.8'
services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-n-foodious-app
    env_file:
      - ./envs/${NODE_ENV:-prod}.env
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    depends_on:
      - mysql
    networks:
      - fast-n-foodious-network
  mysql:
    image: mysql:8.0
    container_name: fast-n-foodious-mysql    
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: $DATABASE_USERNAME
      MYSQL_DATABASE: FAST_N_FOODIOUS
    ports:
      - ${DATABASE_PORT:-3306}:${DATABASE_PORT:-3306}
    volumes:
      - ./scripts/schema:/docker-entrypoint-initdb.d
      - mysql-data:/data/db
    networks:
      - fast-n-foodious-network

volumes:
  mysql-data:
networks:
  fast-n-foodious-network:
    driver: bridge