apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-svc
spec:
  selector:
    app: {{ .Values.application.name }}
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
  - port: 3306

