apiVersion: v1
kind: Service
metadata:
  name: fast-n-foodious-svc
spec:
  selector:
    app: fast-n-foodious
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306

