apiVersion: v1
kind: Service
metadata:
  name: fast-n-foodious-svc
spec:
  selector:
    app: fast-n-foodious-app
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: fast-n-foodious-mysql
spec:
  selector:
    app: fast-n-foodious-mysql
  ports:
  - port: 3306

