-- Criação de banco de dados
CREATE DATABASE IF NOT EXISTS FAST_N_FOODIOUS;

-- Configuração de permissão para usuário da aplicação
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES ON FAST_N_FOODIOUS.* TO 'fnf_user'@'%';
FLUSH PRIVILEGES;

USE FAST_N_FOODIOUS;

-- Criação de tabelas
CREATE TABLE IF NOT EXISTS CLIENTE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  CPF VARCHAR(255) NOT NULL
);
-- indexes para tabela CLIENTE
CREATE UNIQUE INDEX cliente_email_idx ON CLIENTE(EMAIL);
CREATE UNIQUE INDEX cliente_cpf_idx ON CLIENTE(CPF);
