namespace: default

application:
  name: fast-n-foodious
  image: ottero/fast-n-foodious:latest
  resources:
    limits:
      memory: "768Mi"
      cpu: "500m"

service:
  loadbalancer:
    port: 80

mysql:
  name: mysql
  image: mysql:8.0
  resources:
    limits:
      memory: "768Mi"
      cpu: "500m"

configMap:
  data:
    NODE_ENV: prod
    MYSQL_HOST: mysql
    MYSQL_USER: fnf_user

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 70

pv:
  storage: 500Mi
  hostPath: /tmp/lib/mysql

pvc:
  requests:
      storage: 300Mi

secret:
  data:
    MYSQL_PASSWORD: Zm5mX3Bhc3M=
    MYSQL_ROOT_PASSWORD: Zm5mX3Bhc3M=