### Cria um cliente
POST http://localhost:3000/v1/cliente
Content-Type: application/json

{
   "nome": "cliente",
   "email": "cliente@email.com",
   "cpf": "25634428771" 
}

### Consulta cliente por cpf
GET http://localhost:3000/v1/cliente?cpf=256344287772