### Cria um produto
POST http://localhost:3000/v1/produto
Content-Type: application/json

{
  "nome": "Produto Teste",
  "idCategoriaProduto": 1,
  "descricao": "Descrição Produto Teste",
  "preco": 100
}