### Cria um produto
POST http://localhost:3000/v1/produto
Content-Type: application/json

{
  "nome": "Produto Teste",
  "idCategoriaProduto": 1,
  "descricao": "Descrição Produto Teste",
  "preco": 100
}

### Edita um produto
PUT http://localhost:3000/v1/produto/1
Content-Type: application/json

{
  "id": 1,
  "nome": "Produto Teste 23",
  "idCategoriaProduto": 2,
  "descricao": "Descrição Produto Teste 2",
  "preco": 111
}