name: CI
run-name: Pull Request CI
on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing dependencies
        run: npm install
      - name: Running unit tests
        run: npm run test
      - name: Running coverage tests
        run: npm run test:cov
      - name: Running test check
        run: npm run test:check
      - name: Running e2e tests (In-Memory Repositories)
        run: NODE_ENV=local-mock-repository npm run test:e2e
