#!/bin/sh

# Configura para usar o repositorio mockado
setNodeEnvToMock() {
    NODE_ENV_CURRENT=${NODE_ENV}
    export NODE_ENV='local-mock-repository'
}
# Restaura os valores originais
restoreNodeEnv() {
  export NODE_ENV=${NODE_ENV_CURRENT}
  unset NODE_ENV_CURRENT
}

# Função para centralizar a mensagem e exibir em uma caixa
displayBoxedMessage() {
  message=$1
  total_width=80  # Largura total da caixa
  padding=3       # Espaço de preenchimento entre a mensagem e as bordas

  # Ajusta a mensagem para ter o mesmo comprimento total
  message=$(printf "%-${total_width}s" "$message")

  # Gera a linha superior da caixa
  echo "╔$(printf '═%.0s' $(seq 1 $((total_width - 3))))╗"

  # Gera a linha com a mensagem centralizada
  echo "║$(printf "%-${total_width}s" "$message")║"

  # Gera a linha inferior da caixa
  echo "╚$(printf '═%.0s' $(seq 1 $((total_width - 3))))╝"
}

# Termina o programa, retornando a mensagem e status
exitWithMessage() {
  message=$1
  status=$2
  displayBoxedMessage "$message"
  restoreNodeEnv
  exit $status
}

setNodeEnvToMock

echo " 🚀 Executando testes de de integração (modo local mocked).."
npm run test:e2e

e2etestStatus=$?

echo " 🚀 Verificando implementações dos testes.."
npm run test:check -- --silent

# Verifica se os testes unitário falharam
if [ $e2etestStatus -ne 0 ]; then
  exitWithMessage " 🚨 Testes de integração falharam. Abortando o push." 1
fi

exitWithMessage " ✅ Validação pre-push finalizada com sucesso" 0